### ISSUE TITLE
Le lien pour la documentation de l'API est brisé

### ISSUE THREAD

**Issue by mehdiben7** [mna/assnatapi#1]
J'imagine qu'au vu de la date du dernier commit, l'API est un peu rouillée et pourrait être améliorer. Je suis interessé, mais je n'arrive pas à trouver la documentation

**Comment by mna** [comment]
Salut Mehdi,

En effet, je n'ai pas touché à ce repo depuis des lunes! J'ai ajusté le lien, ça devrait fonctionner.

Have fun!
Martin

**Comment by mna** [comment]
Ah, je n'avais pas remarqué que le lien était dans le README aussi, je l'avais juste mis à jour dans la section About du repo. C'est maintenant corrigé dans le README aussi. Je vais archiver le repo car je ne le maintiens plus, mais libre à toi de le faire évoluer!

Martin
